import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
const $ = id => document.getElementById(id);
const settings = {size:3,speed:1,spacing:.06,bevel:.08,roughness:.28,metalness:.05,sticker:.88,intensity:3,ambient:1.5,softness:3};
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(35,1,.1,100);
let renderer;
try {renderer = new THREE.WebGLRenderer({antialias:true,alpha:true});} catch(e) {$('error').hidden=false;$('error').textContent='WebGL is unavailable. Please enable hardware acceleration and reload.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.setClearColor(0x000000,1);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
$('viewport').append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Drag a cube face to turn a layer. Drag the background to orbit. Use two fingers to zoom and pan.');
const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();
const key=new THREE.DirectionalLight(0xffffff,3);key.position.set(4,8,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.1,far:30});key.shadow.bias=-.001;key.shadow.normalBias=.035;key.shadow.radius=3;scene.add(key);
const ambient=new THREE.AmbientLight(0xffffff,1.5);scene.add(ambient);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.23}));floor.rotation.x=-Math.PI/2;floor.position.y=-3;floor.receiveShadow=true;scene.add(floor);
const root=new THREE.Group();scene.add(root);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=5;controls.maxDistance=24;controls.maxPolarAngle=Math.PI*.94;controls.autoRotateSpeed=.7;controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN};
function home(){camera.position.set(7,5.2,8.5);controls.target.set(0,0,0);controls.update();}home();
const colors=[0xeb482d,0xff8724,0xf5f0df,0xf3ce24,0x2670df,0x37a465];
const plastic=new THREE.MeshStandardMaterial({color:0x101113,roughness:.33,metalness:.08});
const pads=colors.map(color=>new THREE.MeshStandardMaterial({color,roughness:settings.roughness,metalness:settings.metalness}));
let cubies=[],bodyGeometry,padGeometry,queue=[],active=null,history=[],mode='idle',completed=0,total=0;
const axes=['x','y','z'];const unit={x:new THREE.Vector3(1,0,0),y:new THREE.Vector3(0,1,0),z:new THREE.Vector3(0,0,1)};
function geometries(){bodyGeometry?.dispose();padGeometry?.dispose();bodyGeometry=new RoundedBoxGeometry(.98,.98,.98,3,Math.max(.001,settings.bevel));padGeometry=new RoundedBoxGeometry(1,1,.025,3,Math.min(.012,Math.max(.001,settings.bevel)));for(const c of cubies){c.children[0].geometry=bodyGeometry;for(const p of c.children.slice(1)){p.geometry=padGeometry;p.scale.set(settings.sticker,settings.sticker,1);}}}
function positionCubies(){const scale=3/settings.size;root.scale.setScalar(scale);for(const c of cubies)c.position.copy(c.userData.grid).multiplyScalar(1+settings.spacing);floor.position.y=-(settings.size/2*(1+settings.spacing)*scale)-.15;}
function build(){queue=[];active=null;history=[];mode='idle';root.clear();cubies=[];geometries();const n=settings.size,half=(n-1)/2;for(let x=0;x<n;x++)for(let y=0;y<n;y++)for(let z=0;z<n;z++){if(x>0&&x<n-1&&y>0&&y<n-1&&z>0&&z<n-1)continue;const c=new THREE.Group();c.userData.grid=new THREE.Vector3(x-half,y-half,z-half);const body=new THREE.Mesh(bodyGeometry,plastic);body.castShadow=true;body.receiveShadow=true;c.add(body);const faces=[[x===n-1,0,[.497,0,0],[0,Math.PI/2,0]],[x===0,1,[-.497,0,0],[0,-Math.PI/2,0]],[y===n-1,2,[0,.497,0],[-Math.PI/2,0,0]],[y===0,3,[0,-.497,0],[Math.PI/2,0,0]],[z===n-1,4,[0,0,.497],[0,0,0]],[z===0,5,[0,0,-.497],[0,Math.PI,0]]];for(const [visible,index,pos,rot] of faces){if(!visible)continue;const pad=new THREE.Mesh(padGeometry,pads[index]);pad.position.set(...pos);pad.rotation.set(...rot);pad.scale.set(settings.sticker,settings.sticker,1);pad.castShadow=true;pad.receiveShadow=true;c.add(pad);}cubies.push(c);root.add(c);}positionCubies();$('sizeCaption').textContent=Array(3).fill(String(n).padStart(2,'0')).join(' × ');updateStatus();}
function solved(){return cubies.every(c=>c.children.slice(1).every(p=>{const normal=new THREE.Vector3(0,0,1).applyQuaternion(p.quaternion).applyQuaternion(c.quaternion);const original=new THREE.Vector3(0,0,1).applyQuaternion(p.quaternion);return normal.dot(original)>.999;}));}
function updateStatus(){const isSolved=solved();$('stateLabel').textContent=mode==='scramble'?'SCRAMBLING':mode==='solve'?'SOLVING':isSolved?'SOLVED':'MIXED';$('moveCount').textContent=`${history.length} move${history.length===1?'':'s'}`;$('activity').textContent=mode==='idle'?'Ready when you are':`${completed} / ${total} turns`;$('scramble').disabled=mode!=='idle'||!!active;$('solve').disabled=mode!=='idle'||!!active||isSolved;for(const id of ['spacing','bevel'])$(id).disabled=mode!=='idle'||!!active;}
function begin(move){const pivot=new THREE.Group();root.add(pivot);root.updateMatrixWorld(true);const selected=cubies.filter(c=>Math.abs(c.userData.grid[move.axis]-move.layer)<.01);for(const c of selected)pivot.attach(c);active={move,pivot,selected,progress:0};updateStatus();}
function finish(){const {move,pivot,selected}=active;pivot.rotation[move.axis]=move.dir*Math.PI/2;pivot.updateMatrixWorld(true);for(const c of selected){root.attach(c);c.userData.grid.applyAxisAngle(unit[move.axis],move.dir*Math.PI/2);for(const axis of axes)c.userData.grid[axis]=Math.round(c.userData.grid[axis]*2)/2;c.position.copy(c.userData.grid).multiplyScalar(1+settings.spacing);c.quaternion.normalize();}root.remove(pivot);if(mode==='solve')history.pop();else history.push({...move});active=null;completed++;if(!queue.length){mode='idle';if(solved())history=[];}updateStatus();}
$('scramble').onclick=()=>{if(active||mode!=='idle')return;mode='scramble';completed=0;total=18+settings.size*3;let previous='';for(let i=0;i<total;i++){let axis;do{axis=axes[Math.floor(Math.random()*3)];}while(axis===previous);previous=axis;queue.push({axis,layer:Math.floor(Math.random()*settings.size)-(settings.size-1)/2,dir:Math.random()<.5?1:-1});}updateStatus();};
$('solve').onclick=()=>{if(active||mode!=='idle'||!history.length)return;mode='solve';queue=history.slice().reverse().map(m=>({...m,dir:-m.dir}));completed=0;total=queue.length;updateStatus();};
$('reset').onclick=()=>{build();home();controls.autoRotate=false;$('rotateView').setAttribute('aria-pressed','false');};$('homeView').onclick=home;$('rotateView').onclick=()=>{$('rotateView').setAttribute('aria-pressed',String(controls.autoRotate=!controls.autoRotate));};
let surfaceTexture=null;
function setTexture(){surfaceTexture?.dispose();surfaceTexture=null;const value=$('texture').value;if(value==='Carbon Fiber'||value==='Brushed Metal'){const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d');ctx.fillStyle='#bcbcbc';ctx.fillRect(0,0,128,128);for(let y=0;y<128;y++){if(value==='Brushed Metal'){ctx.fillStyle=`rgb(${155+(Math.sin(y*78.2)*.5+.5)*90},${155+(Math.sin(y*78.2)*.5+.5)*90},${155+(Math.sin(y*78.2)*.5+.5)*90})`;ctx.fillRect(0,y,128,1);}else for(let x=0;x<128;x+=8){ctx.fillStyle=((Math.floor(x/8)+Math.floor(y/8))%2)?'#767676':'#c5c5c5';ctx.fillRect(x,y,7,1);}}surfaceTexture=new THREE.CanvasTexture(canvas);surfaceTexture.wrapS=surfaceTexture.wrapT=THREE.RepeatWrapping;surfaceTexture.repeat.set(2,2);surfaceTexture.colorSpace=THREE.SRGBColorSpace;}for(const m of pads){m.map=surfaceTexture;m.bumpMap=surfaceTexture;m.bumpScale=value==='Carbon Fiber'?.018:.004;m.needsUpdate=true;}const preset=value==='Matte'?[.88,0]:value==='Brushed Metal'?[.35,.8]:value==='Carbon Fiber'?[.48,.25]:[.28,.05];['roughness','metalness'].forEach((id,i)=>{$(id).value=preset[i];$(id).dispatchEvent(new Event('input'));});}
$('texture').onchange=setTexture;
for(const [id,initial] of Object.entries(settings)){const input=$(id);const update=()=>{settings[id]=Number(input.value);input.style.setProperty('--fill',`${(input.value-input.min)/(input.max-input.min)*100}%`);$(id+'Value').textContent=id==='size'?`${input.value} × ${input.value} × ${input.value}`:id==='sticker'?`${Math.round(input.value*100)}%`:id==='speed'?`${Number(input.value).toFixed(1)}×`:['intensity','ambient'].includes(id)?Number(input.value).toFixed(1):id==='softness'?input.value:Number(input.value).toFixed(2);};input.addEventListener('input',()=>{update();if(id==='size')build();if(id==='spacing'&&!active)positionCubies();if(id==='bevel'&&!active)geometries();if(id==='sticker')for(const c of cubies)for(const p of c.children.slice(1))p.scale.set(settings.sticker,settings.sticker,1);if(id==='roughness'||id==='metalness')for(const m of pads)m[id]=settings[id];key.intensity=settings.intensity;ambient.intensity=settings.ambient;key.shadow.radius=settings.softness;});update();}
$('lightColor').oninput=e=>key.color.set(e.target.value);$('shadows').onchange=e=>{key.castShadow=e.target.checked;floor.visible=e.target.checked;};$('panelToggle').onclick=()=>{const hidden=$('panel').classList.toggle('hidden');$('panelToggle').setAttribute('aria-expanded',String(!hidden));};
// Determine a layer from the visible face normal and the screen-space drag.
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let drag=null;const pointers=new Set();
function hitAt(e){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(cubies,true)[0];}
renderer.domElement.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1){drag=null;controls.enabled=true;return;}if(e.button!==0||active||mode!=='idle')return;const hit=hitAt(e);if(!hit)return;const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);const axis=axes.reduce((a,b)=>Math.abs(normal[a])>Math.abs(normal[b])?a:b);normal.set(0,0,0);normal[axis]=Math.sign(hit.face.normal.clone().transformDirection(hit.object.matrixWorld)[axis]);drag={x:e.clientX,y:e.clientY,point:hit.point.clone(),normal,cubie:hit.object.parent,id:e.pointerId};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)<12)return;const rect=renderer.domElement.getBoundingClientRect();const origin=drag.point.clone().project(camera);let best=null;for(const axis of axes){if(Math.abs(drag.normal[axis])>.5)continue;const tangent=new THREE.Vector3().crossVectors(unit[axis],drag.normal);const projected=drag.point.clone().add(tangent).project(camera);const sx=(projected.x-origin.x)*rect.width,sy=-(projected.y-origin.y)*rect.height;const dot=(sx*dx+sy*dy)/Math.hypot(sx,sy);if(!best||Math.abs(dot)>Math.abs(best.dot))best={axis,dot};}if(best)begin({axis:best.axis,layer:drag.cubie.userData.grid[best.axis],dir:Math.sign(best.dot)});drag=null;});
function endPointer(e){pointers.delete(e.pointerId);drag=null;controls.enabled=true;}renderer.domElement.addEventListener('pointerup',endPointer);renderer.domElement.addEventListener('pointercancel',endPointer);renderer.domElement.addEventListener('lostpointercapture',()=>{drag=null;controls.enabled=true;});
new ResizeObserver(()=>{const {width,height}=$('viewport').getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}).observe($('viewport'));
build();let previous=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-previous)/1000,.05);previous=now;if(!active&&queue.length)begin(queue.shift());if(active){active.progress=Math.min(1,active.progress+dt*settings.speed/.32);const t=active.progress;active.pivot.rotation[active.move.axis]=active.move.dir*Math.PI/2*(t*t*(3-2*t));if(t>=1)finish();}controls.update();renderer.render(scene,camera);});
// Read-only diagnostics for state verification.
window.cubeLab={getState:()=>({size:settings.size,cubies:cubies.length,moves:history.length,solved:solved(),busy:!!active||queue.length>0,positions:cubies.map(c=>c.userData.grid.toArray())})};
